### PR TITLE
refact(core): Move doom settings to `doom.settings` field.

### PR DESCRIPTION
**Pull request by molleweide**
moves settings table into root. `doom.settings.<setting>`

### CODE REVIEW

**Comment by connorgmeehan** [comment]
Thank you for these changes, I'll merge these changes with `v4.1.x` as I don't want to introduce breaking changes without including some new features / updates.  (Mainly mason.nvim / auto installing LSP/DAP/linters etc and including DAP configs).

**Comment by molleweide** [comment]
I will come back here later and add more descriptive notes.

**Comment by molleweide** [comment]
up until here, I am demonstrating how you can create a new mod dir structure.

**Comment by molleweide** [comment]
I propose making a new subdir `features/version_control` in which we have these modules:

```
git_base  | gitsigns / vgit (similar plugins but both have useful stuff)
github_gh        | litee github
github_octo    | github functionality
git_diffview
neogit
lazygit
git_conflicts
git_worktree
git_notifications
```

**Comment by molleweide** [comment]
The reason why some binds stopped working in the demo branch is because I forgot to replace the for loop in the `whichkey` module with tree. Now all binds came back to me. So now tree is fully compatible with any module structure and binds.

**Comment by molleweide** [comment]
I scrapped the `dui` module for now. I am going to finish some more of the functionality when I have time and add it again when some of the more fancy binds has been added.

**Comment by connorgmeehan** [comment]
That's the only feedback I have, everything else looks good to me.  If you address this issue I'll happily merge it in for v4.1 :)  Also let me know if you need (also sorry about the merge conflicts, I had a look through them, apart from the changes to `doom_global.lua`, please take the latest upstream changes and add the `doom.settings` field where necessary.  I can also do this if you like

**Comment by molleweide** [comment]
I cannot see where you put the feedback? Am I missing something or where do I see the feedback?

**Pull request closed without merging**
