### PR TITLE
feat(core): load and manage modules recursively

### PR DESCRIPTION
**Pull request by molleweide**
- Adds `utils/tree.lua` file.
- modifies `is_mod_enabled` -> pass table as arg with the path to module.
- Modifies `core` accordingly + `whichtree` module.
- Allows user to freely structure their modules however they like.
- I have improved documentation. Need feedback. I am not so used to writing documentation.
- !!! I have yet to clean up the logger function so please ignore it for now. Should I split it into another file `utils/tree_logger.lua`?

I feel like `utils/tree` now is in a state where it makes sense for you to have a look at it. Comment with a question mark wherever you feel the code is unclear.

Todo: 

- Update Doom docs.

Current state of my `modules.lua` file : https://github.com/molleweide/doom-nvim/blob/moll_mason/modules.lua

### CODE REVIEW

**Comment by molleweide** [comment]
tell me if I need to drop the `doom.settings` commit

**Comment by connorgmeehan** [comment]
Hey @molleweide, sorry for the delay reviewing this and thank you for the PR.  I think that generalising tree traversal is a good idea but there are some issues with this implementation.  The main one is that I think this helper is doing too much, it's trying to support all use cases with a single implementation.  This makes it a bit confusing to grok and read code as a lot of the code might not be relevant to whatever we're trying to traverse.  Also there is the added performance drop of running un-needed code.  

I think a better solution would be to make `tree.lua` a tree traversal builder. That allows us to easily define tree traversals for whatever our use case.  I think this will make it easier to re-use code, make it easier to read and debug, and provide more specific error messages for whatever data we're passing.
```lua
-- This example implements depth first traversal of doom modules

-- Here we define a new traverser for doom modules, instead of being responsible for the
-- traversal of the tree itself, tree_traverser allows us to build a custom traversal algorithm specifically for our use case.

local modules_traverser = tree_traverser.build({
  -- Builds the traversal function defining how we should move through the tree
  -- @param node any The node itself
  -- @param next function(node: any) Traverse into the traverse_in node, adding the node to the stack
  -- @param traverse_out function() Traverses back a depth, pops the value from the stack
  -- @param err function(message: string) Traverses back a depth, this value is skipped by the handler (see below)
  traverser = function(node, stack, traverse_in, traverse_out, err)
    local parent = stack[#stack]
    local parent_is_section = (parent == nil or (type(parent.key) == "string" and type(parent.node) == "table"))
    if type(node) == "table" and parent_is_section then
      for key, value in pairs(node) do
        traverse_in(key, value) -- Traverse into next layer
      end
    elseif type(node) == "string" and not parent_is_section then
      print(node)
      traverse_out() -- This is a leaf, traverse back a layer
    else
      err(("doom-nvim: Error traversing doom modules in `modules.lua`, unexpected value `%s`."):format(vim.inspect(node))) -- Traverse back a layer but do not pass this value to the handler function.
    end
  end,
  -- Optional debugging function that can be used to
  debug_node = function(node, stack)
    local parent = stack[#stack]
    local indent_str = string.rep("--", #stack)
    local indent_cap = type(node) == "table" and "+" or ">"
    print(("%s%s %s"):format(indent_str, indent_cap, type(node) == "table" and parent.key or node))
  end,
})

-- Example modules
local modules = {
  features = {
    "feature_test",
  },
  langs = {
    "language_test",
    -- 1,
    -- { "error" },
    -- nil,
  },
  -- 2,
  -- { "error" },
  -- nil,
}

-- The second variable is a function to handle each node where we can implement the node handling logic and do the task we need.
-- modules_traverser can be re-used anytime we want to iterate over a modules structure now.
modules_traverser(modules, function(node, stack)
  if type(node) == "string" then
    local path = vim.tbl_map(function(stack_node)
      return type(stack_node.key) == "string" and stack_node.key or stack_node.node
    end, stack)
    local path_string = "doom.modules." .. table.concat(path, ".")

    print(path_string)
  else
  end
end, { debug = doom.logging == "trace" or doom.logging == "debug" })

```

This also makes the implementation of the tree traversal a lot simpler

```lua
local log = require("doom.utils.logging")
local tree_traverser = {
  build = function(builder_opts)
    local traverser = builder_opts.traverser
    local debug_node = builder_opts.debug_node
    local stack = {}
    local result = {}
    -- Traverse out, pops from stack, adds to result
    local traverse_out = function()
      table.remove(stack, #stack)
      table.remove(stack, #stack)
    end
    -- Error does not add to result or anything
    local err = function(message)
      table.remove(stack, #stack)
      local path = vim.tbl_map(function(stack_node)
        return "["..vim.inspect(stack_node.key).."]"
      end, stack)
      print(("%s\n Occursed at key `%s`."):format(message, table.concat(path, "")))
      table.remove(result, #result)
    end
    local traverse_in
    traverse_in = function(key, node)
      table.insert(stack, { key = key, node = node })
      table.insert(result, { node = node, stack = vim.deepcopy(stack) })
      traverser(node, stack, traverse_in, traverse_out, err)
    end

    return function(tree, handler, opts)
      result = {} -- Reset result

      traverser(tree, stack, traverse_in, traverse_out, err)

      if opts.debug and debug_node then
        for _, value in ipairs(result) do
          debug_node(value.node, value.stack)
        end
      end

      for _, value in ipairs(result) do
        handler(value.node, value.stack)
      end
    end
  end,
}
```

I really appreciate the code that you have written so far and the ideas for this generalised traverser.  I think for this to be worth it it needs to be adaptable enough to work for other recursive structures (keymaps, autocommands, commands).  Currently this PR feels like it's adding more complexity than needed to doom-nvim (my proposed solution does a bit as well) and I think the goal should be not to increase LOC too much and write something that is a lot simpler to read.

Also some more general feedback
- Use `string.rep` to build indentation
- I don't think it's worth having multiple logging levels for the debug mode, I think just leave it as `trace` and `debug`
- Maybe instead of a filter there can be a `skip()` function? Not sure if `prev()` will already cover this use-case.

**Comment by connorgmeehan** [comment]
To add to this, the capabilities of this code are really cool and full featured but I think it's just not a right fit to go into the shared `utils` folder because it has too many features and code that wont be used by most users.  I think it's better to make a really lightweight way of traversing trees in `utils` and then implement something like this into your `dui` modules.  Kind of the same idea of breaking a monolith into micro services.

Also you don't have to copy my solution but it's just an example of a more stripped down version that can be adapted to different use-cases, keen to see what you come up with :)

**Comment by molleweide** [comment]
@connorgmeehan allright so now I have tweaked your traversal in a few minor ways to make it work a little bit more flexible. Now I get it to print the whole `modules` table as it should. 

This is awesome! Thanks a lot for showing me your version. I still have to study it some more because I am not used to
the pattern where you return a function.

## issues solved

1. The modules traverser func did not travel / pop back up when having finished a subtable.
    I solved this by adding a `traverse_out` call att the end of the looping each node table.

2. Now I also handle the case of an empty table, so that you don't have to worry about this.

## links

Here is my modules quick reference: https://github.com/molleweide/doom-nvim/blob/molleweide/modules.lua
and here is the code: https://github.com/molleweide/doom-nvim/blob/molleweide/scratch/tree_connor.lua

## next steps 

Now we need to incorporate this into doom. Do you have any suggestions on how we should place these files.
My suggestion:
- put the `tree_traverser` in a service (maybe also under utils)
- move the `modules_traverser` to under utils.

and then replace every iteration over modules with the call to the `modules_traverser`, ie. in:
1. `core/config`
2. `core/modules`
3. `whichkey` module.
4. etc.

After this is done, then I'll redo the `doom.settings` PR.

**Comment by molleweide** [comment]
And after all of this, I'll tweak `dui` to fit with the new traverser.

**Comment by molleweide** [comment]
I replaced all instances of `tree` in my `molleweide` branch with `traverser`.

**Pull request closed without merging**
